# Generated by Django 4.1.3 on 2022-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Zip',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
